language: python
matrix:
  include:
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: false
    - python: 3.8
      dist: xenial
      sudo: false
    - python: 3.9
      dist: xenial
      sudo: false

install:
  - python setup.py develop
  - pip install -r requirements-dev.txt

script:
  - flake8 .
  - coverage run --source=typeform --omit=typeform/test/*.py setup.py test

after_success:
  - coveralls